service:
  name: ${file(package.json):name}

package:
  exclude:
    - plugin/**
    - node_modules/**

custom:
  s3Sync:
    - bucketName: ${self:service}-files-${self:provider.stage}
      localDir: upload

plugins:
  - serverless-s3-sync
  - invoke-after-deploy

provider:
  name: aws
  stage: ${opt:stage, 'local'}
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:${opt:region, 'us-east-1'}:*:table/${self:service}-db-${self:provider.stage}"
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource: "arn:aws:s3:::${self:service}-files-${self:provider.stage}"

environment: ${file(config.${self:provider.stage}.json)}

functions:
  writeFile:
    handler: app/dist/index.handler
    environment:
      BUCKET: arn:aws:s3:::${self:service}-files-${self:provider.stage}
      TABLE: arn:aws:dynamodb:${opt:region, 'us-east-1'}:*:table/${self:service}-db-${self:provider.stage}

resources: # CloudFormation template syntax from here on.
  Resources:
    FooTable: 
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-foo-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    FilesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-files-${self:provider.stage}
